name: Dev Deployment

on:
  push:
    branches: [ develop ]

jobs:
  dev:
    
    runs-on: ubuntu-latest
    environment: DEV

    
    steps:
      
      - uses: actions/checkout@v3
      
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      
      - name: Run Tests
        run: |
          pip install pytest
          pytest tests/ || echo "No tests found or tests failed"

      
      - name: Build Docker Image
        run: docker build -t flask-dev-app .

      
      - name: Verify Environment
        run: echo "I am running a job in the DEV environment"

      
      - name: Deploy to Development Environment
        run: |
          echo "Deploying the Docker image..."
          docker run -d --name flask-dev-container -p 5000:5000 flask-dev-app
